from flask import Flask, render_template, request, jsonify, send_file
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from fpdf import FPDF
import json
import os
import datetime

app = Flask(__name__)

# --- 1. BNS AI BRAIN (Knowledge Base) ---
bns_database = [
    {"section": "BNS Section 103 (Murder)", "text": "Murder killed shot dead stabbed to death intentional killing assassination homicide dead body"},
    {"section": "BNS Section 109 (Attempt to Murder)", "text": "Attempt to murder tried to kill fired gun shot at me stabbed critical injury attack with knife"},
    {"section": "BNS Section 303 (Theft)", "text": "Theft stealing stolen pickpocket wallet mobile laptop took away without consent thief robbery"},
    {"section": "BNS Section 304 (Snatching)", "text": "Snatching chain snatching mobile snatching grabbed necklace pulled mangalsutra ran away on bike"},
    {"section": "BNS Section 115 (Voluntarily Causing Hurt)", "text": "Hit me beat me punched slapped physical fight injury bleeding pain attacked with hands kicked"},
    {"section": "BNS Section 126 (Wrongful Restraint)", "text": "Blocked my way stopped me from going restricted movement held me stopped car blocked road"},
    {"section": "BNS Section 318 (Cheating)", "text": "Cheating fraud scam money fraud bank fraud online fraud digital arrest lie deceived dishonest"},
    {"section": "BNS Section 351 (Criminal Intimidation)", "text": "Threatened to kill threat warning intimidation blackmail fear of death threatened my family"},
    {"section": "BNS Section 281 (Rash Driving)", "text": "Rash driving driving fast overspeeding hit and run negligent driving accident car crash bike crash"},
    {"section": "BNS Section 74 (Outrage Modesty)", "text": "Outrage modesty touched inappropriately bad touch groping molested harassment public transport"},
    {"section": "BNS Section 137 (Kidnapping)", "text": "Kidnapping took child away missing child abducted took away forcefully ransom demand missing person"}
]

# Train Model on Startup
documents = [item['text'] for item in bns_database]
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)

# --- 2. DATABASE MANAGEMENT ---
DB_FILE = 'database.json'

def load_data():
    if not os.path.exists(DB_FILE): return []
    try:
        with open(DB_FILE, 'r') as f: return json.load(f)
    except: return []

def save_data(record):
    data = load_data()
    data.append(record)
    with open(DB_FILE, 'w') as f: json.dump(data, f, indent=4)

def recommend_section(text):
    if not text: return "Unknown"
    query_vec = vectorizer.transform([text])
    sim = cosine_similarity(query_vec, tfidf_matrix).flatten()
    best = sim.argmax()
    # Threshold ensures random text doesn't trigger a severe section
    return bns_database[best]['section'] if sim[best] > 0.1 else "Manual Review Required"

# --- 3. ROUTES ---
@app.route('/')
def home(): return render_template('home.html')

@app.route('/user')
def user_page(): return render_template('user.html')

@app.route('/admin')
def admin_page():
    data = load_data()
    # Reverse list to show newest first
    return render_template('admin.html', cases=data[::-1], total=len(data))

@app.route('/analyze', methods=['POST'])
def analyze():
    data = request.json
    section = recommend_section(data['text'])
    
    record = {
        "id": datetime.datetime.now().strftime("%Y%m%d%H%M%S"),
        "date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "text": data['text'],
        "section": section,
        "lat": data['lat'],
        "lon": data['lon']
    }
    save_data(record)
    return jsonify(record)

# --- 4. OFFICIAL PDF REPORT GENERATOR ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'OFFICIAL POLICE INCIDENT LOG', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by Smart-FIR AI System | Confidential', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

@app.route('/download_pdf')
def download_pdf():
    data = load_data()
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=10)
    
    # Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(35, 10, "Date", 1, 0, 'C', 1)
    pdf.cell(55, 10, "Recommended Law", 1, 0, 'C', 1)
    pdf.cell(50, 10, "Location", 1, 0, 'C', 1)
    pdf.cell(50, 10, "Status", 1, 1, 'C', 1)

    # Table Rows
    for case in data:
        pdf.cell(35, 10, str(case['date']), 1)
        
        # Handle long text for section
        section_short = str(case['section']).split('(')[0][:25]
        pdf.cell(55, 10, section_short, 1)
        
        loc = f"{case['lat']:.4f}, {case['lon']:.4f}" if case['lat'] else "Unknown"
        pdf.cell(50, 10, loc, 1)
        pdf.cell(50, 10, "Logged", 1, 1)

    filename = "Official_FIR_Report.pdf"
    pdf.output(filename)
    return send_file(filename, as_attachment=True)

if __name__ == '__main__':
    app.run(debug=True, port=5000)